package com.docs.autogen.config

import org.springframework.beans.factory.annotation.Value
import org.springframework.context.annotation.Configuration
import org.springframework.context.annotation.Primary
import springfox.documentation.swagger.web.SwaggerResource
import springfox.documentation.swagger.web.SwaggerResourcesProvider
import springfox.documentation.swagger2.annotations.EnableSwagger2
import java.util.*

@Primary
@Configuration
@EnableSwagger2
class SwaggerSpecConfig : SwaggerResourcesProvider {

    @Value("\${swagger-ui.location}")
    lateinit var location: String

    override fun get(): MutableList<SwaggerResource> {
        val swaggerResource = SwaggerResource()
        swaggerResource.location = location
        swaggerResource.name = "Autogenerated API Spec"
        return Collections.singletonList(swaggerResource)
    }
}